// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHCv_iAmiD9KNIbweZqvEHGbxYVd-RpFo',
    appId: '1:252219952392:web:7d289da0282bab98fdf0bd',
    messagingSenderId: '252219952392',
    projectId: 'frontend-dd6d1',
    authDomain: 'frontend-dd6d1.firebaseapp.com',
    storageBucket: 'frontend-dd6d1.appspot.com',
    measurementId: 'G-GBB2WD4Q3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCypuqYfy2-28GaFQuY67fxxnH2tU_ioZQ',
    appId: '1:252219952392:android:976790accef71536fdf0bd',
    messagingSenderId: '252219952392',
    projectId: 'frontend-dd6d1',
    storageBucket: 'frontend-dd6d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeshvNBv08stV4vqejkUKp0wHChEo-Va0',
    appId: '1:252219952392:ios:96ead806bf4a1787fdf0bd',
    messagingSenderId: '252219952392',
    projectId: 'frontend-dd6d1',
    storageBucket: 'frontend-dd6d1.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeshvNBv08stV4vqejkUKp0wHChEo-Va0',
    appId: '1:252219952392:ios:cbfbe1243c2d307bfdf0bd',
    messagingSenderId: '252219952392',
    projectId: 'frontend-dd6d1',
    storageBucket: 'frontend-dd6d1.appspot.com',
    iosBundleId: 'com.example.frontend.RunnerTests',
  );
}
